# Generated by Django 4.1.3 on 2022-12-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image_path',
            field=models.ImageField(upload_to='gallery/images/'),
        ),
    ]
