# Generated by Django 4.1.3 on 2022-12-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='properties/images/'),
        ),
    ]
